name: Greenlight_CICD_Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Cleanup workspace
        run: sudo rm -rf ${{ github.workspace }}/*

      - name: Remove old env files
        run: rm -f .env || true

      - name: Create .env file
        run: echo "${{ secrets.ENV }}" >> .env

      - name: Check for compose.yml
        run: |
          if [ -f "compose.yml" ]; then
          echo "compose.yml found"
          else
          echo "compose.yml not found"
          exit 1
          fi

      - name: Rebuild & Restart using docker compose
        run: |
          echo "Rebuilding and restarting services..."
          docker compose -f compose.yml config  # Validate the compose file
          if ! docker compose -f compose.yml up -d --build; then
            echo "Docker Compose failed"
            docker compose -f compose.yml logs  # Print logs if it fails
            exit 1
          fi

      - name: Remove any dangling images
        run: docker image prune -f

      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed!"
